# Generated by Django 6.1 on 2026-08-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='allow_self_registration',
            field=models.BooleanField(default=True, help_text='Let new staff create their own account from the login page.'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='require_registration_approval',
            field=models.BooleanField(default=True, help_text='Self-registered accounts stay disabled until an Administrator or Manager enables them. Turn this off only on a trusted network.'),
        ),
    ]
