# Generated by Django 6.1 on 2026-08-27 17:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_storesetting_allow_self_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount applied to this product on every sale, as a percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_number',
            field=models.CharField(blank=True, db_index=True, help_text='Snapshot of the customer number, so old invoices stay correct.', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='product_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='existing_customer_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Applied automatically to customers with a previous completed purchase. Cashiers cannot change or override it.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{6,20}$', 'Enter a valid phone number (digits, spaces, +, -, and brackets only).')], verbose_name='customer number'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='business_name',
            field=models.CharField(default="O'dell Tech Shopping", max_length=120),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='max_cashier_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Legacy cashier discount ceiling; kept for historical records.', max_digits=5),
        ),
    ]
