# Generated by Django 6.1 on 2026-08-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_backfill_employee_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Link to the product photo. Shown beside the name on every screen.', max_length=500),
        ),
    ]
