# Generated by Django 4.0.3 on 2026-09-06 01:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What this unit cost the business, captured at the moment of sale. Profit reporting uses this rather than the current cost_price on the product, so editing a price later cannot rewrite past margins. NULL means the sale predates this field: those lines are reported as "cost unknown" and excluded from profit rather than being valued at a cost that was never paid.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
